config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    # Redirests signing out users back to sign-in
    get 'users', to: 'devise/sessions#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  devise_for :users
  resources :users, path: '/admin/users', as: :admin_users
  # post 'create_user' => 'users#create', as: :create_user   
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do 
      resources :posts do
        resources :post_ratings, only: [:create]
        resources :comments
        resources :post_reports, only: [:new, :index, :create, :destroy]
      end
    end
  end

  get :search_with_gem, to: 'search#search_with_gem', as: :search_with_gem
end

app/views/partials/_header.html.erb
<%= render 'partials/navbar' %>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Bhutanese IMDB', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
        <%= link_to 'Home', root_path, class: "navbar-brand" %>
        <% if current_user.present?%>
          <%= link_to 'ADD Content', new_post_path, class: "navbar-brand" %>
        <%end%>
        <% if current_user.present? && current_user.admin? %>
          <%= link_to 'Admin Panel', posts_path, class: "navbar-brand" %>
        <% end %>
    </div>
    <%= link_to 'Filter', search_with_gem_path, class: "navbar-brand" %>
      
       <% if current_user.nil?%>
         <%= link_to 'Sign Up', new_user_registration_path, class: "navbar-brand" %>
          <%= link_to 'Sign In', new_user_session_path, class: "navbar-brand", method: :get %>
        <% else %>
          <%= link_to 'Log Out', destroy_user_session_path, class: "navbar-brand" %>
    <% end %>
       <% if current_user.present? %>
          <%= link_to "Profile", admin_user_path(id: current_user.id), class: "navbar-brand" %>
        <% end %>
  </div>
</nav>