config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    # Redirests signing out users back to sign-in
    get 'users', to: 'devise/sessions#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  devise_for :users
  resources :users, path: '/admin/users', as: :admin_users
  # post 'create_user' => 'users#create', as: :create_user   
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do 
      resources :posts do
        resources :post_ratings, only: [:create]
        resources :comments
        resources :post_reports, only: [:new, :index, :create, :destroy]
      end
    end
  end

  get :search_with_gem, to: 'search#search_with_gem', as: :search_with_gem
end

app/models/post.rb
class Post < ApplicationRecord
  include ContentType
  include Rails.application.routes.url_helpers

  has_one_attached :poster, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :post_ratings, dependent: :destroy
  has_many :post_reports, dependent: :destroy
  has_many :movie_members_names, dependent: :destroy
  accepts_nested_attributes_for :movie_members_names

  has_many_attached :images, dependent: :destroy
  has_one_attached :trailer, dependent: :destroy

  belongs_to :user, class_name: 'User', foreign_key: 'user_id'

  validates :post_tittle, :release_date, presence: true
  validates :poster,
            content_type: IMAGE_TYPE,
            size: { less_than_or_equal_to: 5.megabytes, message: 'must be within 5MB in size' }

  validates :trailer,
            content_type: {
              in: VIDEO_TYPE,
              message: "formats supported are #{VIDEO_TYPE.join(', ')}."
            },
            size: { less_than_or_equal_to: 500.megabytes, message: 'must be within 500MB in size' }
  after_create :generate_post_url

  before_save :calculate_average_rating

  private

  def generate_post_url
    update_attribute(:link, "#{Global.backend_server.base_url}/#{post_path(self)}")
  end

  def blank_star
    5 - rating.to_i
  end

  def calculate_average_rating
    if  self.post_ratings.present?
      self.score = self.post_ratings.sum(:rating)/self.post_ratings.count
    end
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  
  before_action :authenticate_user!, except: [:show, :index]
  before_action :find_post, only: %i(edit show update destroy)

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def index
    @posts = if params[:flag] == 'rating'
              Post.where("score > 3")
            elsif params[:flag] == 'relesed_date'
              Post.order(release_date: :desc)
            else
              Post.order(created_at: :desc)
            end
  end

  def show
    @post = Post.with_attached_images.find(params[:id])
    @comments = @post.comments.order(created_at: :desc)
  end

  def update
    if @post.update(post_params)
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    if @post.destroy!
      redirect_to posts_path
    else
      redirect_to root_path
    end
  end

  def show_comment
    @comments = @post.comments.includes(:user).order(created_at: :desc)
    render :index
  end

  private

  def post_params
    params.require(:post).permit(
      :name,
      :description,
      :release_date,
      :link,
      :trailer,
      :poster,
      :director_name,
      :producer_name,
      :cast_name,
      images: [],
    ).merge({ user_id: current_user.id })
  end

  def find_post
    @post = Post.find(params[:id]) 
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :find_post, only: %i(edit show update destroy)

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def index
    @posts = if params[:flag] == 'rating'
              Post.where("score > 3")
            elsif params[:flag] == 'relesed_date'
              Post.order(release_date: :desc)
            else
              Post.order(created_at: :desc)
            end
  end

  def show
    @post = Post.with_attached_images.find(params[:id])
    @comments = @post.comments.order(created_at: :desc)
  end

  def update
    if @post.update(post_params)
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    if @post.destroy!
      redirect_to posts_path
    else
      redirect_to root_path
    end
  end

  def show_comment
    @comments = @post.comments.includes(:user).order(created_at: :desc)
    render :index
  end

  private

  def post_params
    params.require(:post).permit(
      :name,
      :description,
      :release_date,
      :link,
      :trailer,
      :poster,
      :director_name,
      :producer_name,
      :cast_name,
      images: [],
    ).merge({ user_id: current_user.id })
  end

  def find_post
    @post = Post.find(params[:id]) 
  end
end

app/views/posts/_form.html.erb
<%= simple_form_for post do |f| %>
  <%= f.input :name,  required: true%>
  <%= f.input :director_name %>
  <%= f.input :producer_name%>
  <%= f.input :cast_name %>
  <%= f.input :release_date, as: :date, html5: true %>
  <%= f.input :description%>

  <br>
  <%= f.label :poster, 'Upload Poster'%>
  <%= f.file_field :poster, required: true, accept: ContentType::IMAGE_TYPE %>
  <br>
  <%= f.label :trailer, 'Upload Movie Tariler'%>
  <%= f.file_field :trailer, required: true, accept: ContentType::VIDEO_TYPE %>
  <br>
  <%= f.label :images, 'Upload Movie related images'%>
  <%= f.file_field :images, multiple: true, accept: ContentType::IMAGE_TYPE %>
  <br>
  <%= f.button :submit, class: "btn-success mt-3" %>
<% end %>

app/views/posts/edit.html.erb
<div class="container my-5">
  <div class="card">
    <div class="card-body">
      <h1>Update Movie Information</h1>
      <%= render 'form', post: @post %>
      <br>
      <%= link_to 'BACK', posts_path, class: "btn btn-info btn-sm" %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container my-4">
  <div class="card">
    <div class="card-body">
      <h1 class="view-h1"></h1>
      <%= link_to 'User List ', admin_users_path, class: "btn btn-primary" %>
       <table class="table table-hover">
       <h1> Movie List </h1>
          <thead>
            <tr>
              <th scope="col">Poster</th>
              <th scope="col">Name</th>
              <th scope="col">Reports</th>
              <th scope="col">Actions</th>
            </tr>
          </thead>
        <tbody>
        <%  if @posts.present? %>
          <% @posts.all.each do |post| %>
            <tr>
              <td>
                <div class="posts-index-img d-inline">
                  <% if post.poster.attached? %>
                    <%= image_tag(post.poster, class: "index-img") %>
                  <% else %>
                    <%= image_tag('default_book_avatar.jpeg', class: "index-img") %>
                  <% end %>
                </div>
              </td>
              <td><%= post.name %></td>
              <td>
                <% if post.post_reports.present? %>
                  <%= button_to 'Reports', post_post_reports_path(post), method: :get %>
                <% else %>
                  None
                <% end %>
              </td>
              <td>
                <%= button_to 'Show', post_path(post), method: :get %>
                <%= button_to 'Delete',  post_path(post), method: :delete %>
              </td>
          <% end %>
        <% end %>
            </tr>
         </tbody>
      </table>
      <br/>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container my-5">
  <div class="card">
    <div class="card-body">
      <h1>Add Movies</h1>
      <%= render 'form', post: @post %>
      <br>    
      <%= link_to 'BACK', posts_path, class: "btn btn-info btn-sm" %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container my-5">
  <div class="card">
    <div class="card-body ">
     <h1 ><%= @post.name %></h1>
      <% if @post.trailer.attached? %>
        <%= video_tag(url_for(@post.trailer), style: 'width: 80%', controls: true) %>
      <% end %>
       <div class="text-warning">
         Rating <%= @post.score%>/5.0 
         <%= render 'post_ratings/form', post: @post %>
         <%= link_to 'Report', new_post_post_report_path(@post), class: "btn btn-danger" %>
       </div>
       <p> <span style="color:blue">Release Date: </span> <%= @post.release_date%></p>
        <h2>Details</h2>
       <p><span style="color:blue">All Cast: </span><%= @post.director_name %></p>
       <p><span style="color:blue">Director: </span><%= @post.director_name %></p>
       <p><span style="color:blue">Producer: </span><%= @post.producer_name %></p>
       <h3><span style="color:Red">Story Line</span></h3>
       <p><%= @post.description %></p>
      <div>
      </div>
      <% if current_user.present? && current_user.id == @post.user_id %>
        <%= link_to 'Edit', edit_post_path(@post), class: "btn btn-primary" %> |
        <%= button_to 'Delete', post_path(@post), class: "btn btn-danger", method: :delete %>
      <% end %>
    </div>
  </div>
  <h1>Related Images </h1>
    <% if @post.images.attached? %>
      <% @post.images.each do |image| %>
        <%= image_tag(url_for(image), class: "index-img") %>
      <% end %>
    <% end%>

<h1>Comment</h1>

<div class="container">
  <%= render 'comments/form', post: @post %>
  <% @comments.each do |comment| %>
    <%= render 'comments/comment', post: @post, comment: comment %>
  <% end %>
</div>