config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    # Redirests signing out users back to sign-in
    get 'users', to: 'devise/sessions#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  devise_for :users
  resources :users, path: '/admin/users', as: :admin_users
  # post 'create_user' => 'users#create', as: :create_user   
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do 
      resources :posts do
        resources :post_ratings, only: [:create]
        resources :comments
        resources :post_reports, only: [:new, :index, :create, :destroy]
      end
    end
  end

  get :search_with_gem, to: 'search#search_with_gem', as: :search_with_gem
end

app/models/post_report.rb
class PostReport < ApplicationRecord
    belongs_to :post, class_name: 'Post', foreign_key: 'post_id'
    belongs_to :user, class_name: 'User', foreign_key: 'user_id'

    validates :message, presence: true
end

app/controllers/api/v1/post_reports_controller.rb
class Api::V1::PostReportsController < ApplicationController
  
  before_action :authenticate_user!
  before_action :find_post
  
  def index
    @post_reports = @post.post_reports.order(created_at: :desc)
  end
  def create
    @post_report = @post.post_reports.new(post_report_params)
    if @post_report.save!
      PostReportMailer.new_post_report_email(@post, @post_report, current_user.email).deliver_later
      flash[:success] = "Thank you for your report! We'll get contact you soon!"
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def destroy
    @post_report = @post.post_reports.find(params[:id])
    @post_report.destroy!
    redirect_to post_post_reports_path(@post)
  end

  def post_report_params
    params.require(:post_report).permit(:message, :post_id).merge(user_id: current_user.id)
  end

  def find_post
    @post = Post.find_by(id: params[:post_id])
  end
end

app/controllers/post_reports_controller.rb
class PostReportsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_post
  
  def index
    @post_reports = @post.post_reports.order(created_at: :desc)
  end
  def create
    @post_report = @post.post_reports.new(post_report_params)
    if @post_report.save!
      PostReportMailer.new_post_report_email(@post, @post_report, current_user.email).deliver_later
      flash[:success] = "Thank you for your report! We'll get contact you soon!"
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def destroy
    @post_report = @post.post_reports.find(params[:id])
    @post_report.destroy!
    redirect_to post_post_reports_path(@post)
  end

  def post_report_params
    params.require(:post_report).permit(:message, :post_id).merge(user_id: current_user.id)
  end

  def find_post
    @post = Post.find_by(id: params[:post_id])
  end
end

app/views/post_reports/index.html.erb
<div class="container my-4">
  <div class="card">
    <div class="card-body">
      <h1 class="view-h1"></h1>
       <table class="table table-hover">
       <%= link_to 'Back',  posts_path %>
          <thead>
          <h1>Report List</h1>
            <tr>
              <th scope="col">Movie Nam</th>
              <th scope="col">Reporter</th>
              <th scope="col">URL</th>
              <th scope="col">Reason</th>
              <th scope="col">Actions</th>
            </tr>
          </thead>
        <tbody>

          <% @post.post_reports.all.each do |post_report| %>
            <tr>
              <td><%= @post.name %></td>
              <td>
              <%= link_to @post.user.name,  admin_user_path( @post.user.name) %>
              </td>
              <td><%= @post.link %></td>
              <td><%= post_report.message %></td>
              <td>
                <%= button_to 'Delete',  post_post_report_path(@post, post_report), method: :delete %>
              </td>
            <% end %>
            </tr>
         </tbody>
      </table>
      <br/>
    </div>
  </div>
</div>

app/views/post_reports/new.html.erb
<div class="container my-5">
  <div class="card">
    <div class="card-body">
    <%= form_with(model: [@post, @post.post_reports.build]) do |f| %>
      <div class="form-group">
        <%= f.text_area :message, placeholder: 'New comment', require: true, class: 'form-control' %>
      </div><br>
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
    <% end %>
   </div> 
 </div>
</div>